import React from 'react';
import { Icons } from './constants';
import { Radar, RadarChart, PolarGrid, PolarAngleAxis, ResponsiveContainer, BarChart, Bar, XAxis, YAxis, Tooltip, Cell } from 'recharts';
import { CourseRecommendations } from './CourseRecommendations';

export const AnalysisReport = ({ analysis, config, onReset }) => {
    const radarData = [
        { subject: 'Clarity', A: analysis.clarity || 0, fullMark: 100 },
        { subject: 'Confidence', A: analysis.confidence || 0, fullMark: 100 },
        { subject: 'Communication', A: analysis.communication || 0, fullMark: 100 },
        { subject: 'Technical', A: analysis.technicalKnowledge || 0, fullMark: 100 },
    ];

    const scoreData = [
        { name: 'Clarity', score: analysis.clarity || 0 },
        { name: 'Confidence', score: analysis.confidence || 0 },
        { name: 'Communication', score: analysis.communication || 0 },
        { name: 'Technical', score: analysis.technicalKnowledge || 0 },
    ];

    const COLORS = ['#1c1c1c', '#407E86', '#A58D66', '#666'];

    return (
        <div className="max-w-6xl mx-auto space-y-12 animate-in fade-in slide-in-from-bottom-8 duration-1000">
            <div className="flex flex-col md:flex-row justify-between items-end gap-8 border-b-[3px] border-[#1c1c1c] pb-10">
                <div className="space-y-4">
                    <div className="flex items-center gap-4">
                        <span className="text-[10px] font-black uppercase tracking-[0.4em] bg-[#1c1c1c] text-white px-4 py-1.5 shadow-[4px_4px_0px_#ccc]">EVALUATION_COMPLETE</span>
                        {analysis.duration && (
                            <span className="text-[10px] font-black font-grotesk border-[2px] border-[#1c1c1c] px-4 py-1.5 text-[#1c1c1c]">
                                SESSION_TIME: {analysis.duration}
                            </span>
                        )}
                    </div>
                    <h2 className="text-6xl font-black text-[#1c1c1c] tracking-tight font-montreal uppercase">Analysis Report</h2>
                </div>
                <button
                    onClick={onReset}
                    className="px-10 py-5 bg-white border-[3px] border-[#1c1c1c] text-[#1c1c1c] font-black uppercase text-[10px] tracking-[0.2em] shadow-[8px_8px_0px_#1c1c1c] hover:bg-[#1c1c1c] hover:text-white hover:-translate-y-2 hover:shadow-[12px_12px_0px_#ccc] transition-all font-grotesk"
                >
                    BACK
                </button>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-3 gap-10">
                {/* Score Summary */}
                <div className="lg:col-span-2 bg-white border-[3px] border-[#1c1c1c] p-12 shadow-[12px_12px_0px_#1c1c1c]/5 flex flex-col md:flex-row items-center gap-16 relative overflow-hidden group">
                    <div className="text-center md:text-left shrink-0 z-10">
                        <h4 className="text-[10px] font-black uppercase tracking-[0.4em] text-[#1c1c1c]/40 mb-2 font-grotesk">Overall Score</h4>
                        <div className="text-[10rem] font-black text-[#1c1c1c] leading-none tracking-tighter font-montreal">
                            {analysis.overallScore || 0}
                        </div>
                        <p className="max-w-xs text-[#1c1c1c]/50 text-[10px] font-black uppercase tracking-widest leading-relaxed mt-4 font-grotesk">
                            Neural assessment generated by Fair Hiring Intelligence.
                        </p>
                    </div>
                    <div className="flex-1 w-full h-[400px] relative z-10" style={{ minWidth: 0 }}>
                        <ResponsiveContainer width="100%" height="100%">
                            <RadarChart cx="50%" cy="50%" outerRadius="80%" data={radarData}>
                                <PolarGrid stroke="#eee" />
                                <PolarAngleAxis dataKey="subject" tick={{ fill: '#1c1c1c', fontSize: 10, fontWeight: 900, letterSpacing: '0.1em' }} />
                                <Radar
                                    name="Candidate"
                                    dataKey="A"
                                    stroke="#1c1c1c"
                                    fill="#1c1c1c"
                                    fillOpacity={0.1}
                                    strokeWidth={3}
                                />
                            </RadarChart>
                        </ResponsiveContainer>
                    </div>
                    <div className="absolute top-0 right-0 p-8 text-[8rem] font-black text-[#1c1c1c]/5 pointer-events-none uppercase">STATS</div>
                </div>

                {/* Skill Metrics */}
                <div className="bg-white border-[3px] border-[#1c1c1c] p-12 shadow-[12px_12px_0px_#1c1c1c]/5">
                    <h3 className="text-[11px] font-black mb-10 inline-block border-b-[3px] border-[#1c1c1c] pb-2 uppercase tracking-[0.3em] font-grotesk">
                        Skill Segmentation
                    </h3>
                    <div className="w-full h-[320px] relative" style={{ minWidth: 0 }}>
                        <ResponsiveContainer width="100%" height="100%">
                            <BarChart data={scoreData} layout="vertical" margin={{ left: -30, right: 30 }}>
                                <XAxis type="number" hide domain={[0, 100]} />
                                <YAxis dataKey="name" type="category" width={100} tick={{ fontSize: 9, fill: '#1c1c1c', fontWeight: 900, letterSpacing: '0.1em' }} axisLine={false} tickLine={false} />
                                <Tooltip
                                    cursor={{ fill: '#f5f5f5' }}
                                    content={({ active, payload }) => {
                                        if (active && payload && payload.length) {
                                            return (
                                                <div className="bg-[#1c1c1c] p-4 shadow-[4px_4px_0px_#ccc] border border-black">
                                                    <p className="text-white font-black text-[10px] uppercase tracking-widest leading-none">
                                                        {payload[0].name} : {payload[0].value}
                                                    </p>
                                                </div>
                                            );
                                        }
                                        return null;
                                    }}
                                />
                                <Bar dataKey="score" radius={[0, 0, 0, 0]} barSize={40}>
                                    {scoreData.map((entry, index) => (
                                        <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />
                                    ))}
                                </Bar>
                            </BarChart>
                        </ResponsiveContainer>
                    </div>
                </div>
            </div>


            <div className="grid grid-cols-1 md:grid-cols-2 gap-10">
                <div className="bg-white border-[3px] border-[#1c1c1c] p-12 shadow-[12px_12px_0px_#1c1c1c]/5">
                    <h3 className="text-2xl font-black text-[#1c1c1c] mb-10 flex items-center gap-4 uppercase font-montreal">
                        <Icons.Check className="w-8 h-8" /> Demonstrable Strengths
                    </h3>
                    <ul className="space-y-6">
                        {analysis.strengths && analysis.strengths.length > 0 ? (
                            analysis.strengths.map((s, i) => (
                                <li key={i} className="flex items-start gap-4 text-[#1c1c1c]/80 font-black font-grotesk text-sm uppercase">
                                    <div className="mt-1 w-2.5 h-2.5 bg-[#1c1c1c] shrink-0" />
                                    {s}
                                </li>
                            ))
                        ) : (
                            <li className="text-[#1c1c1c]/40 font-black font-grotesk text-[10px] uppercase italic">
                                INSUFFICIENT DATA POINTS_
                            </li>
                        )}
                    </ul>
                </div>

                <div className="bg-[#1c1c1c] p-12 shadow-[12px_12px_0px_#ccc]">
                    <h3 className="text-2xl font-black text-white mb-10 flex items-center gap-4 uppercase font-montreal">
                        <Icons.Sparkles className="w-8 h-8" /> Development Areas
                    </h3>
                    <ul className="space-y-6">
                        {analysis.recommendations && analysis.recommendations.length > 0 ? (
                            analysis.recommendations.map((r, i) => (
                                <li key={i} className="flex items-start gap-4 text-white/80 font-black font-grotesk text-sm uppercase">
                                    <div className="mt-1 w-2.5 h-2.5 bg-white shrink-0" />
                                    {r}
                                </li>
                            ))
                        ) : (
                            <li className="text-white/40 font-black font-grotesk text-[10px] uppercase italic">
                                NO CRITICAL GROWTH VECTORS IDENTIFIED_
                            </li>
                        )}
                    </ul>
                </div>
            </div>

            <div className="bg-white border-[3px] border-[#1c1c1c] p-12 shadow-[12px_12px_0px_#1c1c1c]/5">
                <div className="flex justify-between items-center mb-10">
                    <h3 className="text-3xl font-black tracking-tight font-montreal uppercase underline decoration-[#1c1c1c] underline-offset-8">Session Transcript</h3>
                    <div className="px-5 py-2 border-[2px] border-[#1c1c1c] text-[9px] font-black uppercase font-grotesk">Historical Record</div>
                </div>
                <div className="max-h-[600px] overflow-y-auto pr-8 space-y-8 font-grotesk">
                    {analysis.transcript.split('\n').map((line, i) => {
                        const isInterviewer = line.startsWith('Interviewer:');
                        return (
                            <div key={i} className={`p-8 border-[2px] transition-all ${isInterviewer ? 'bg-[#1c1c1c] text-white border-[#1c1c1c]' : 'bg-[#E6E6E3] border-[#1c1c1c] text-[#1c1c1c]'}`}>
                                <span className={`text-[8px] font-black uppercase tracking-[0.4em] block mb-3 ${isInterviewer ? 'text-white/50' : 'text-[#1c1c1c]/50'}`}>
                                    {isInterviewer ? 'SYSTEM_NODE_AI' : 'SUBJECT_HUMAN_V1'}
                                </span>
                                <p className="text-sm font-black uppercase leading-relaxed tracking-tight">
                                    {line.replace(/^(Candidate|Interviewer):\s*/, '')}
                                </p>
                            </div>
                        );
                    })}
                </div>
            </div>

            {config?.role && (
                <CourseRecommendations role={config.role} />
            )}

            <div className="py-16 text-center">
                <p className="text-[#1c1c1c]/20 text-[10px] font-black uppercase tracking-[0.8em]">SYSTEM_VERSION_1.0 // FAIR_HIRING_NETWORK</p>
            </div>
        </div>
    );
};
